# Generated by Django 5.1.1 on 2024-11-02 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='科目コード')),
                ('name', models.CharField(max_length=50, verbose_name='科目名')),
                ('assigned_year', models.PositiveIntegerField(verbose_name='配当年次')),
                ('credits', models.PositiveIntegerField(verbose_name='単位数')),
                ('category1', models.CharField(max_length=4, verbose_name='判定区分1')),
                ('category2', models.CharField(blank=True, max_length=4, verbose_name='判定区分2')),
                ('category3', models.CharField(blank=True, max_length=4, verbose_name='判定区分3')),
                ('pe_flag', models.CharField(blank=True, max_length=4, verbose_name='体育フラグ')),
                ('ab_flag', models.CharField(blank=True, max_length=4, verbose_name='A/Bフラグ')),
                ('foreign_student_flag', models.BooleanField(default=False, verbose_name='留学生科目')),
                ('pre_sub', models.CharField(blank=True, max_length=8, verbose_name='前提科目')),
            ],
        ),
        migrations.CreateModel(
            name='AcquiredCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=0)),
                ('category1', models.CharField(blank=True, max_length=4)),
                ('category2', models.CharField(blank=True, max_length=4)),
                ('category3', models.CharField(blank=True, max_length=4)),
                ('pe_flag', models.CharField(blank=True, max_length=4)),
                ('ab_flag', models.CharField(blank=True, max_length=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hantei.subjecttable')),
            ],
        ),
        migrations.CreateModel(
            name='UserAcquiredCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_subjects', models.DateTimeField(auto_now_add=True)),
                ('acquired_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hantei.acquiredcredits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
