# Generated by Django 5.1.1 on 2024-10-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(choices=[('1', '1年'), ('2', '2年'), ('3', '3年'), ('4', '4年')], max_length=1)),
                ('undergraduate', models.CharField(choices=[('management', '経営学部'), ('commerce', '商学部'), ('human_sciences', '人間科学部')], max_length=20)),
                ('course', models.CharField(choices=[('management', '経営学部'), ('commerce', '商学部'), ('human_sciences', '人間科学部')], max_length=20)),
                ('english_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20)),
                ('repeating_a_course', models.CharField(choices=[('あり', 'あり'), ('なし', 'なし')], max_length=20)),
                ('First_and_second_terms_semester', models.CharField(choices=[('前期', '前期'), ('後期', '後期')], max_length=20)),
                ('Seminar_membership', models.CharField(choices=[('加入', '入っている'), ('未加入', '入っていない')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
