# Generated by Django 5.1.1 on 2024-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('business_management', 'ビジネスマネジメント'), ('finance', 'ファイナンス'), ('accounting', '会計学'), ('marketing', 'マーケティング'), ('psychology', '心理学'), ('sociology', '社会学')], max_length=20),
        ),
    ]
