# Generated by Django 5.1.1 on 2024-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('corporate_management', '企業経営'), ('management_law', '経営法務'), ('Entrepreneurship_and_Business_Succession', '起業・事業承継'), ('information', '情報'), ('finance', '金融'), ('accounting', '会計'), ('marketing', 'マーケティング'), ('psychology', '人間科学専攻（心理・コミュニケーションコース）'), ('sociology', '人間科学専攻（社会・ライフデザインコース）'), ('Child_Education', '児童教育専攻')], max_length=40),
        ),
    ]
